"""Markdown report generator."""

from pathlib import Path
from typing import Dict

from ..model.aggregator import RepoScore, FileScore


class MarkdownReporter:
    """Generates Markdown reports of AI detection results."""

    def __init__(self, config: Dict = None):
        """Initialize reporter.

        Args:
            config: Configuration dict
        """
        self.config = config or {}
        self.top_n_files = self.config.get('top_n_files', 10)
        self.include_code_context = self.config.get('include_code_context', False)

    def generate(self, repo_score: RepoScore, output_path: Path = None) -> str:
        """Generate Markdown report.

        Args:
            repo_score: RepoScore with detection results
            output_path: Optional path to save markdown file

        Returns:
            Markdown report string
        """
        lines = []

        # Header
        lines.append("# AI Code Detection Report")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append(f"**Repository:** `{repo_score.repo_path}`")
        lines.append("")

        # Verdict box
        verdict = self._get_verdict(repo_score.ai_probability)
        prob_percent = repo_score.ai_probability * 100
        conf_percent = repo_score.confidence * 100

        lines.append(f"**AI Probability:** {prob_percent:.1f}%")
        lines.append(f"**Confidence:** {conf_percent:.1f}%")
        lines.append(f"**Verdict:** {verdict}")
        lines.append("")

        # Visual bar
        bar = self._create_probability_bar(repo_score.ai_probability)
        lines.append(bar)
        lines.append("")

        # Component scores
        lines.append("## Component Scores")
        lines.append("")
        lines.append("| Component | Score | Bar |")
        lines.append("|-----------|-------|-----|")

        components = [
            ("Stylometry", repo_score.stylometry_score),
            ("Structural", repo_score.structural_score),
            ("History", repo_score.history_score),
        ]

        for name, score in components:
            bar = self._create_small_bar(score)
            lines.append(f"| {name} | {score*100:.1f}% | {bar} |")

        lines.append("")

        # Statistics
        lines.append("## Repository Statistics")
        lines.append("")
        lines.append(f"- **Files Analyzed:** {repo_score.total_files_analyzed}")
        lines.append(f"- **Lines of Code:** {repo_score.total_lines_analyzed:,}")
        lines.append("")

        # Language distribution
        if repo_score.language_distribution:
            lines.append("**Languages:**")
            lines.append("")
            for lang, count in sorted(repo_score.language_distribution.items(), key=lambda x: x[1], reverse=True):
                lines.append(f"- {lang}: {count} files")
            lines.append("")

        # Top suspicious files
        lines.append("## Top Suspicious Files")
        lines.append("")

        if repo_score.file_scores:
            lines.append("| File | AI Probability | Key Indicators |")
            lines.append("|------|----------------|----------------|")

            for file_score in repo_score.file_scores[:self.top_n_files]:
                prob = file_score.ai_probability * 100
                indicators = self._format_indicators(file_score.feature_explanations)
                lines.append(f"| `{file_score.file_path}` | {prob:.1f}% | {indicators} |")

            lines.append("")

            # Detailed file analysis
            lines.append("## Detailed File Analysis")
            lines.append("")

            for file_score in repo_score.file_scores[:5]:  # Top 5 detailed
                lines.append(f"### {file_score.file_path}")
                lines.append("")
                lines.append(f"**AI Probability:** {file_score.ai_probability*100:.1f}%")
                lines.append("")

                if file_score.feature_explanations:
                    lines.append("**Indicators:**")
                    lines.append("")
                    for feature, value in sorted(file_score.feature_explanations.items(), key=lambda x: x[1], reverse=True):
                        feature_name = self._format_feature_name(feature)
                        lines.append(f"- **{feature_name}:** {value*100:.1f}%")
                    lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*This report was generated by AI Code Detector*")
        lines.append("")
        lines.append("**Note:** This is a probabilistic analysis and should not be used as sole evidence.")
        lines.append("AI detection is most reliable when combined with code review and other verification methods.")

        report = "\n".join(lines)

        # Save to file if path provided
        if output_path:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w') as f:
                f.write(report)

        return report

    def _get_verdict(self, probability: float) -> str:
        """Get human-readable verdict."""
        if probability >= 0.8:
            return "🔴 Very likely AI-generated"
        elif probability >= 0.6:
            return "🟠 Likely AI-generated"
        elif probability >= 0.4:
            return "🟡 Possibly AI-assisted"
        elif probability >= 0.2:
            return "🟢 Possibly human-written"
        else:
            return "✅ Likely human-written"

    def _create_probability_bar(self, probability: float) -> str:
        """Create ASCII probability bar."""
        width = 40
        filled = int(probability * width)
        empty = width - filled

        bar = "█" * filled + "░" * empty
        return f"`[{bar}] {probability*100:.1f}%`"

    def _create_small_bar(self, score: float) -> str:
        """Create small ASCII bar."""
        width = 20
        filled = int(score * width)
        empty = width - filled

        return "█" * filled + "░" * empty

    def _format_indicators(self, explanations: Dict[str, float]) -> str:
        """Format feature explanations as compact string."""
        if not explanations:
            return "-"

        # Get top 2 indicators
        sorted_features = sorted(explanations.items(), key=lambda x: x[1], reverse=True)[:2]

        indicators = []
        for feature, value in sorted_features:
            name = self._format_feature_name(feature)
            indicators.append(name)

        return ", ".join(indicators)

    def _format_feature_name(self, feature: str) -> str:
        """Format feature name for display."""
        # Convert snake_case to Title Case
        return feature.replace('_', ' ').title()
