"""SARIF 2.1.0 export for GitHub code scanning (#13).

Schema: SARIF **2.1.0** (OASIS), ``$schema`` =
``https://json.schemastore.org/sarif-2.1.0.json``. GitHub code scanning
accepts this version only.

Verdict → SARIF ``level`` mapping:

====================  ===========  =========================================
file AI probability   level        rule
====================  ===========  =========================================
>= 0.80               ``error``    ``aicd/file/ai-generated``
>= 0.60               ``warning``  ``aicd/file/ai-generated``
>= min (0.40)         ``note``     ``aicd/file/ai-generated``
< min                 (no result)
====================  ===========  =========================================

Agent-scan findings map ``high``→``error``, ``warning``/``medium``→``warning``,
``info``/``low``→``note`` under ``aicd/agent/<type>``. Repository-level
findings that have no file (for example commit-history attribution) cannot be
placed by GitHub, so they go in ``runs[0].properties.repositoryFindings``.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path, PurePosixPath
from typing import Any, Dict, List, Optional

SARIF_VERSION = "2.1.0"
SARIF_SCHEMA = "https://json.schemastore.org/sarif-2.1.0.json"
INFO_URI = "https://github.com/BenjaminSRussell/Ai_code_detector"
FILE_RULE_ID = "aicd/file/ai-generated"
DEFAULT_MIN_PROBABILITY = 0.4

_AGENT_RULES = {
    "ai_attribution": ("AI tool attribution in history",
                       "Commit metadata or messages attribute changes to an AI coding tool."),
    "duplication": ("Cross-file duplication",
                    "Near-duplicate code across files, a common artifact of generated code."),
    "satd": ("Self-admitted technical debt",
             "TODO/FIXME/HACK style markers left in the code."),
    "performance_hotspot": ("Performance hotspot",
                            "Function with high complexity or nested loops that is likely slow."),
}
_SEVERITY_LEVEL = {"critical": "error", "high": "error", "error": "error",
                   "medium": "warning", "warning": "warning",
                   "low": "note", "info": "note", "note": "note"}


def _version() -> str:
    try:
        from importlib.metadata import version
        return version("ai-code-detector")
    except Exception:
        return "0.0.0"


def probability_level(p: float, min_probability: float = DEFAULT_MIN_PROBABILITY) -> Optional[str]:
    if p >= 0.8:
        return "error"
    if p >= 0.6:
        return "warning"
    if p >= min_probability:
        return "note"
    return None


def _uri(path: str) -> str:
    return PurePosixPath(str(path).replace("\\", "/")).as_posix()


def _fingerprint(*parts: Any) -> str:
    return hashlib.sha256("\x1f".join(map(str, parts)).encode("utf-8")).hexdigest()[:32]


def _location(path: str, line: Optional[int] = None) -> Dict:
    loc: Dict[str, Any] = {"physicalLocation": {
        "artifactLocation": {"uri": _uri(path), "uriBaseId": "%SRCROOT%"},
    }}
    loc["physicalLocation"]["region"] = {"startLine": max(1, int(line or 1))}
    return loc


def _run(rules: List[Dict], results: List[Dict], properties: Dict) -> Dict:
    return {
        "tool": {"driver": {
            "name": "aicd",
            "fullName": "AI Code Detector",
            "version": _version(),
            "semanticVersion": _version(),
            "informationUri": INFO_URI,
            "rules": rules,
        }},
        "originalUriBaseIds": {"%SRCROOT%": {"description": {"text": "Scanned repository root"}}},
        "invocations": [{"executionSuccessful": True}],
        "results": results,
        "properties": properties,
    }


def _wrap(run: Dict) -> Dict:
    return {"$schema": SARIF_SCHEMA, "version": SARIF_VERSION, "runs": [run]}


def _write(doc: Dict, output_path: Optional[Path]) -> str:
    text = json.dumps(doc, indent=2)
    if output_path:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(text, encoding="utf-8")
    return text


_FILE_RULE = {
    "id": FILE_RULE_ID,
    "name": "LikelyAIGeneratedFile",
    "shortDescription": {"text": "File is likely AI-generated"},
    "fullDescription": {"text": (
        "Stylometric, structural, and (optionally) ML signals suggest this file was "
        "generated by an AI assistant. This is a probabilistic signal for review "
        "prioritisation, not proof.")},
    "helpUri": INFO_URI + "#sarif-export-github-code-scanning",
    "help": {"text": "Review the file for unverified generated code. Add vendored or "
                     "generated paths to .aicdignore to suppress them."},
    "defaultConfiguration": {"level": "warning"},
    "properties": {"tags": ["ai-detection", "maintainability"], "precision": "low"},
}


class SarifReporter:
    """RepoScore → SARIF (``aicd scan --format sarif``)."""

    def __init__(self, min_probability: float = DEFAULT_MIN_PROBABILITY):
        self.min_probability = min_probability

    def build(self, repo_score) -> Dict:
        results = []
        for fs in sorted(repo_score.file_scores, key=lambda f: -f.ai_probability):
            level = probability_level(fs.ai_probability, self.min_probability)
            if level is None:
                continue
            top = sorted((fs.feature_explanations or {}).items(), key=lambda kv: -abs(kv[1]))[:3]
            signals = ", ".join(f"{k} ({v:.2f})" for k, v in top)
            text = f"AI probability {fs.ai_probability * 100:.1f}%."
            if signals:
                text += f" Top signals: {signals}."
            explanation = getattr(fs, "explanation", None)
            if explanation:
                text += f" {explanation}"
            results.append({
                "ruleId": FILE_RULE_ID,
                "ruleIndex": 0,
                "level": level,
                "message": {"text": text},
                "locations": [_location(fs.file_path)],
                "partialFingerprints": {"aicdFile/v1": _fingerprint(FILE_RULE_ID, _uri(fs.file_path))},
                "properties": {
                    "ai_probability": round(fs.ai_probability, 4),
                    "stylometry_score": round(fs.stylometry_score, 4),
                    "structural_score": round(fs.structural_score, 4),
                },
            })
        props = {
            "repository_ai_probability": round(repo_score.ai_probability, 4),
            "confidence": round(repo_score.confidence, 4),
            "files_analyzed": repo_score.total_files_analyzed,
            "min_probability": self.min_probability,
        }
        suppressed = getattr(repo_score, "suppressed", None)
        if suppressed:
            props["suppressed_count"] = suppressed.get("count", 0)
        return _wrap(_run([_FILE_RULE], results, props))

    def generate(self, repo_score, output_path: Optional[Path] = None) -> str:
        return _write(self.build(repo_score), output_path)


class FindingsSarifWriter:
    """ScanFindings (agent-scan) → SARIF."""

    def build(self, findings) -> Dict:
        types = sorted({f.type for f in findings.findings})
        rules, index = [], {}
        for t in types:
            name, desc = _AGENT_RULES.get(t, (t.replace("_", " ").title(), f"Agent-scan finding: {t}"))
            index[t] = len(rules)
            rules.append({
                "id": f"aicd/agent/{t}",
                "name": "".join(w.title() for w in t.split("_")),
                "shortDescription": {"text": name},
                "fullDescription": {"text": desc},
                "helpUri": INFO_URI + "#sarif-export-github-code-scanning",
                "properties": {"tags": ["ai-detection", "agent-scan"]},
            })
        results, repo_level = [], []
        for f in findings.findings:
            if not f.file or f.file.startswith("("):
                repo_level.append({"type": f.type, "severity": f.severity, "description": f.description})
                continue
            rule_id = f"aicd/agent/{f.type}"
            result = {
                "ruleId": rule_id,
                "ruleIndex": index[f.type],
                "level": _SEVERITY_LEVEL.get(str(f.severity).lower(), "warning"),
                "message": {"text": f.description},
                "locations": [_location(f.file, f.line)],
                "partialFingerprints": {
                    "aicdFinding/v1": _fingerprint(rule_id, _uri(f.file), f.function or "", f.description)},
            }
            if f.evidence:
                result["properties"] = {"evidence": f.evidence}
            results.append(result)
        props: Dict[str, Any] = {"repository_ai_probability": round(findings.ai_probability, 4)}
        if repo_level:
            props["repositoryFindings"] = repo_level
        suppressed = getattr(findings, "suppressed", None)
        if suppressed:
            props["suppressed_count"] = suppressed.get("count", 0)
        return _wrap(_run(rules, results, props))

    def generate(self, findings, output_path: Optional[Path] = None) -> str:
        return _write(self.build(findings), output_path)
