"""Detection of explicit AI-tool attribution markers in commit messages."""

import re
from typing import Dict, List
from dataclasses import dataclass

from ingest.git_loader import RepoInfo


@dataclass
class AttributionMatch:
    """A commit whose message matched a known AI-attribution pattern."""
    commit_sha: str
    pattern_matched: str
    message_snippet: str


@dataclass
class AttributionFeatures:
    """AI attribution signal extracted from commit history."""
    has_ai_attribution: bool
    match_ratio: float
    matches: List[AttributionMatch]


class AttributionAnalyzer:
    """Scans commit messages for known AI coding-tool attribution markers."""

    DEFAULT_PATTERNS = [
        r"Co-Authored-By:\s*Claude\s*<[^>]*anthropic\.com>",
        r"Co-Authored-By:\s*.*[Cc]opilot",
        r"Co-Authored-By:\s*.*[Cc]ursor",
        r"Co-Authored-By:\s*.*[Cc]odex",
        r"Generated with Claude Code",
        r"Generated by GitHub Copilot",
        r"🤖 Generated with",
    ]

    def __init__(self, config: Dict = None):
        self.config = config or {}
        custom_patterns = self.config.get('ai_attribution_patterns', [])
        self.patterns = [
            re.compile(p, re.IGNORECASE) for p in self.DEFAULT_PATTERNS + custom_patterns
        ]

    def analyze_repo(self, repo_info: RepoInfo) -> AttributionFeatures:
        """Scan repository commit history for AI-attribution markers.

        Args:
            repo_info: Repository information with commit history

        Returns:
            AttributionFeatures
        """
        if not repo_info.commits:
            return AttributionFeatures(has_ai_attribution=False, match_ratio=0.0, matches=[])

        matches = []

        for commit in repo_info.commits:
            for pattern in self.patterns:
                if pattern.search(commit.message):
                    matches.append(AttributionMatch(
                        commit_sha=commit.sha,
                        pattern_matched=pattern.pattern,
                        message_snippet=commit.message.strip()[:200],
                    ))
                    break

        match_ratio = len(matches) / len(repo_info.commits)

        return AttributionFeatures(
            has_ai_attribution=len(matches) > 0,
            match_ratio=match_ratio,
            matches=matches,
        )
